# Generated by Django 6.0.1 on 2026-03-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_orders', models.IntegerField()),
                ('total_customers', models.IntegerField()),
                ('conversion_rate', models.FloatField()),
                ('avg_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_age_months', models.IntegerField()),
                ('initial_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
