# Generated by Django 6.0.1 on 2026-03-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardstats',
            name='monthly_revenue',
            field=models.JSONField(default=list),
        ),
    ]
