# Generated by Django 6.0.1 on 2026-03-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboardstats_monthly_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardstats',
            name='category_orders',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dashboardstats',
            name='category_revenue',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dashboardstats',
            name='monthly_orders',
            field=models.JSONField(default=list),
        ),
    ]
